name: new-workflow
on: [workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       run: echo '${{ toJSON(github)}}'

     - name: Dump GitHub context
       run: echo '${{ toJSON(runner)}}'
     - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          
     - run: echo "Status ${{ job.status }}"

     - name: run linting
       uses: super-linter/super-linter/slim@v5 
       env:
         DEFAULT_BRANCH: main
         # To report GitHub Actions status checks
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
         DISABLE_ERRORS: true 
